// Speaker Driver & Passive Radiator Studio Web Engine

let audioCtx = null;
let carrierOsc = null;
let amOsc = null;
let amGain = null;
let masterGain = null;
let analyser = null;
let animFrameId = null;
let isPlayingLive = false;

// DOM Elements
const targetDriverSelect = document.getElementById('targetDriver');
const carrierFreqInput = document.getElementById('carrierFreq');
const carrierFreqLabel = document.getElementById('carrierFreqLabel');
const carrierValueDisp = document.getElementById('carrierValue');
const freqTicks = document.getElementById('freqTicks');
const targetHelp = document.getElementById('targetHelp');
const crossoverIndicator = document.getElementById('crossoverIndicator');

const amMinFreqInput = document.getElementById('amMinFreq');
const amMinValueDisp = document.getElementById('amMinValue');
const volumeInput = document.getElementById('volume');
const volumeValueDisp = document.getElementById('volumeValue');

const btnPlayLive = document.getElementById('btnPlayLive');
const btnStopLive = document.getElementById('btnStopLive');
const btnPlayPattern = document.getElementById('btnPlayPattern');
const btnDownloadWav = document.getElementById('btnDownloadWav');

const canvas = document.getElementById('audioCanvas');
const canvasCtx = canvas.getContext('2d');
const patternTimeline = document.getElementById('patternTimeline');

// Radiator Sequences
const radiatorPattern = [
    { type: 'sweep', duration: 8.0, pause: 1.0, start: 35, end: 75, label: '🔍 Resonance Sweep' },
    { type: 'pulse', duration: 6.0, pause: 0.5, freq: 52, pulseHz: 6, label: '💥 Max Excursion (52Hz)' },
    { type: 'pulse', duration: 6.0, pause: 0.5, freq: 58, pulseHz: 10, label: '🌊 Heavy Wave (58Hz)' },
    { type: 'pulse', duration: 6.0, pause: 1.0, freq: 45, pulseHz: 4, label: '🌀 Deep Pulsing (45Hz)' }
];

function getAudioContext() {
    if (!audioCtx) {
        audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    }
    if (audioCtx.state === 'suspended') {
        audioCtx.resume();
    }
    return audioCtx;
}

function handleDriverChange() {
    const isRadiator = targetDriverSelect.value === 'radiator';
    if (isRadiator) {
        carrierFreqLabel.textContent = 'Resonance Frequency (Hz)';
        carrierFreqInput.min = '30';
        carrierFreqInput.max = '80';
        carrierFreqInput.step = '1';
        carrierFreqInput.value = '52';
        carrierValueDisp.textContent = '52 Hz';
        freqTicks.innerHTML = '<span>30 Hz</span><span>52 Hz (Resonance Peak)</span><span>80 Hz</span>';
        targetHelp.innerHTML = 'The top/bottom rubber disc is a <strong>Passive Radiator</strong>. It moves via internal pneumatic air pressure generated by 40-65 Hz sub-bass frequencies.';
        crossoverIndicator.textContent = 'Target: Passive Radiator Active (52 Hz)';
        btnPlayLive.innerHTML = '<span class="btn-icon">▶</span> Test Radiator Vibration';
    } else {
        carrierFreqLabel.textContent = 'Carrier Frequency (Hz)';
        carrierFreqInput.min = '14000';
        carrierFreqInput.max = '21000';
        carrierFreqInput.step = '100';
        carrierFreqInput.value = '18500';
        carrierValueDisp.textContent = '18,500 Hz';
        freqTicks.innerHTML = '<span>14 kHz (Audible)</span><span>18.5 kHz (Silent Cutoff)</span><span>21 kHz (Ultrasonic)</span>';
        targetHelp.innerHTML = 'High frequencies (> 15 kHz) pass 100% through the crossover into the tweeter dome while remaining practically silent to human ears.';
        crossoverIndicator.textContent = 'Target: Tweeter Driver Active (18.5 kHz)';
        btnPlayLive.innerHTML = '<span class="btn-icon">▶</span> Test Tweeter Burst';
    }
    renderTimeline();
    updateDisplays();
}

function updateDisplays() {
    const isRadiator = targetDriverSelect.value === 'radiator';
    if (isRadiator) {
        carrierValueDisp.textContent = `${carrierFreqInput.value} Hz`;
    } else {
        carrierValueDisp.textContent = `${parseInt(carrierFreqInput.value).toLocaleString()} Hz`;
    }
    amMinValueDisp.textContent = `${amMinFreqInput.value} Hz`;
    volumeValueDisp.textContent = `${volumeInput.value}%`;

    if (carrierOsc && audioCtx && isPlayingLive) {
        carrierOsc.frequency.setValueAtTime(parseFloat(carrierFreqInput.value), audioCtx.currentTime);
    }
    if (masterGain && audioCtx && isPlayingLive) {
        masterGain.gain.setValueAtTime((parseFloat(volumeInput.value) / 100.0) * 0.85, audioCtx.currentTime);
    }
}

function renderTimeline() {
    patternTimeline.innerHTML = '';
    radiatorPattern.forEach((step, idx) => {
        const div = document.createElement('div');
        div.className = 'timeline-step';
        div.id = `step-${idx}`;
        div.innerHTML = `
            <div class="step-header">Step ${idx + 1}: ${step.label}</div>
            <div class="step-details">${step.type === 'sweep' ? `sweep: ${step.start}Hz ➔ ${step.end}Hz` : `freq: ${step.freq} Hz`}</div>
            <div class="step-details">duration: ${step.duration}s</div>
        `;
        patternTimeline.appendChild(div);
    });
}

// Preset Handlers
document.querySelectorAll('.btn-preset').forEach(btn => {
    btn.addEventListener('click', (e) => {
        const preset = e.target.getAttribute('data-preset');
        targetDriverSelect.value = 'radiator';
        handleDriverChange();

        if (preset === 'radiator_sweep') {
            carrierFreqInput.value = 52;
            playPatternSequence();
            return;
        } else if (preset === 'radiator_max') {
            carrierFreqInput.value = 52;
            amMinFreqInput.value = 6;
        } else if (preset === 'radiator_heavy') {
            carrierFreqInput.value = 45;
            amMinFreqInput.value = 4;
        } else if (preset === 'radiator_fast') {
            carrierFreqInput.value = 60;
            amMinFreqInput.value = 12;
        }
        updateDisplays();
        startLiveAudio();
    });
});

function setupVisualizer() {
    if (!analyser) return;
    analyser.fftSize = 1024;
    const bufferLength = analyser.frequencyBinCount;
    const dataArray = new Uint8Array(bufferLength);

    function draw() {
        animFrameId = requestAnimationFrame(draw);
        analyser.getByteFrequencyData(dataArray);

        canvasCtx.fillStyle = '#060911';
        canvasCtx.fillRect(0, 0, canvas.width, canvas.height);

        const barWidth = (canvas.width / bufferLength) * 2.5;
        let x = 0;

        for (let i = 0; i < bufferLength; i++) {
            const barHeight = (dataArray[i] / 255.0) * canvas.height * 0.85;
            const approxFreq = (i * (audioCtx ? audioCtx.sampleRate : 44100)) / analyser.fftSize;

            if (approxFreq < 100) {
                canvasCtx.fillStyle = '#ff007f'; // Vibrant Pink for Passive Radiator Sub-Bass
            } else if (approxFreq > 15000) {
                canvasCtx.fillStyle = '#00f2fe';
            } else {
                canvasCtx.fillStyle = '#1e293b';
            }

            canvasCtx.fillRect(x, canvas.height - barHeight, barWidth, barHeight);
            x += barWidth + 1;
        }
    }

    if (!animFrameId) draw();
}

function startLiveAudio() {
    stopAudio();
    const ctx = getAudioContext();

    const freq = parseFloat(carrierFreqInput.value);
    const pulseHz = parseFloat(amMinFreqInput.value);
    const volume = (parseFloat(volumeInput.value) / 100.0) * 0.85;

    carrierOsc = ctx.createOscillator();
    carrierOsc.type = 'sine';
    carrierOsc.frequency.setValueAtTime(freq, ctx.currentTime);

    amOsc = ctx.createOscillator();
    amOsc.type = 'sine';
    amOsc.frequency.setValueAtTime(pulseHz, ctx.currentTime);

    amGain = ctx.createGain();
    amGain.gain.setValueAtTime(0.45, ctx.currentTime);

    masterGain = ctx.createGain();
    analyser = ctx.createAnalyser();

    // 10ms taper
    masterGain.gain.setValueAtTime(0.0001, ctx.currentTime);
    masterGain.gain.exponentialRampToValueAtTime(volume, ctx.currentTime + 0.010);

    amOsc.connect(amGain);
    amGain.connect(masterGain.gain);

    carrierOsc.connect(masterGain);
    masterGain.connect(analyser);
    analyser.connect(ctx.destination);

    carrierOsc.start();
    amOsc.start();
    isPlayingLive = true;

    btnPlayLive.classList.add('btn-accent');
    setupVisualizer();
}

function stopAudio() {
    if (carrierOsc) {
        try {
            if (masterGain && audioCtx) {
                masterGain.gain.setValueAtTime(masterGain.gain.value, audioCtx.currentTime);
                masterGain.gain.exponentialRampToValueAtTime(0.0001, audioCtx.currentTime + 0.010);
            }
            setTimeout(() => {
                if (carrierOsc) carrierOsc.stop();
                if (amOsc) amOsc.stop();
                carrierOsc = null;
                amOsc = null;
            }, 12);
        } catch (e) {}
    }
    isPlayingLive = false;
    btnPlayLive.classList.remove('btn-accent');
}

function playPatternSequence() {
    stopAudio();
    const ctx = getAudioContext();
    let startTime = ctx.currentTime + 0.05;

    analyser = ctx.createAnalyser();
    analyser.connect(ctx.destination);
    setupVisualizer();

    radiatorPattern.forEach((step, idx) => {
        const stepElem = document.getElementById(`step-${idx}`);
        const duration = step.duration;
        const pause = step.pause;
        const vol = (parseFloat(volumeInput.value) / 100.0) * 0.85;

        const timeUntilStart = (startTime - ctx.currentTime) * 1000;
        setTimeout(() => {
            document.querySelectorAll('.timeline-step').forEach(el => el.classList.remove('active'));
            if (stepElem) stepElem.classList.add('active');
        }, Math.max(0, timeUntilStart));

        const cOsc = ctx.createOscillator();
        cOsc.type = 'sine';

        if (step.type === 'sweep') {
            cOsc.frequency.setValueAtTime(step.start, startTime);
            cOsc.frequency.linearRampToValueAtTime(step.end, startTime + duration);
        } else {
            cOsc.frequency.setValueAtTime(step.freq, startTime);
            const aOsc = ctx.createOscillator();
            aOsc.type = 'sine';
            aOsc.frequency.setValueAtTime(step.pulseHz, startTime);
            const aGain = ctx.createGain();
            aGain.gain.setValueAtTime(0.45, startTime);
            aOsc.connect(aGain);
            aGain.connect(mGain.gain);
            aOsc.start(startTime);
            aOsc.stop(startTime + duration);
        }

        const mGain = ctx.createGain();
        const taper = 0.010;
        mGain.gain.setValueAtTime(0.0001, startTime);
        mGain.gain.exponentialRampToValueAtTime(vol, startTime + taper);
        mGain.gain.setValueAtTime(vol, startTime + duration - taper);
        mGain.gain.exponentialRampToValueAtTime(0.0001, startTime + duration);

        cOsc.connect(mGain);
        mGain.connect(analyser);

        cOsc.start(startTime);
        cOsc.stop(startTime + duration);

        startTime += duration + pause;
    });

    const totalDurationMs = (startTime - ctx.currentTime) * 1000;
    setTimeout(() => {
        document.querySelectorAll('.timeline-step').forEach(el => el.classList.remove('active'));
    }, Math.max(0, totalDurationMs));
}

function downloadWavFile() {
    const sampleRate = 44100;
    let totalSamples = 0;

    radiatorPattern.forEach(step => {
        totalSamples += Math.floor((step.duration + step.pause) * sampleRate);
    });

    const samples = new Float32Array(totalSamples);
    let sampleIdx = 0;

    radiatorPattern.forEach(step => {
        const vibeNum = Math.floor(step.duration * sampleRate);
        const pauseNum = Math.floor(step.pause * sampleRate);
        const volume = 0.85;
        const fadeLen = Math.floor(sampleRate * 0.010);

        if (step.type === 'sweep') {
            let phase = 0.0;
            for (let i = 0; i < vibeNum; i++) {
                const progress = i / vibeNum;
                const curFreq = step.start + (step.end - step.start) * progress;
                phase += 2.0 * Math.PI * curFreq * (1.0 / sampleRate);
                const carrier = Math.sin(phase);

                let fade = 1.0;
                if (i < fadeLen) {
                    fade = 0.5 * (1.0 - Math.cos((Math.PI * i) / fadeLen));
                } else if (i >= vibeNum - fadeLen) {
                    fade = 0.5 * (1.0 - Math.cos((Math.PI * (vibeNum - 1 - i)) / fadeLen));
                }

                samples[sampleIdx++] = volume * carrier * fade;
            }
        } else {
            for (let i = 0; i < vibeNum; i++) {
                const t = i / sampleRate;
                const carrier = Math.sin(2.0 * Math.PI * step.freq * t);
                const amMod = 0.1 + 0.9 * 0.5 * (1.0 + Math.sin(2.0 * Math.PI * step.pulseHz * t - Math.PI / 2.0));

                let fade = 1.0;
                if (i < fadeLen) {
                    fade = 0.5 * (1.0 - Math.cos((Math.PI * i) / fadeLen));
                } else if (i >= vibeNum - fadeLen) {
                    fade = 0.5 * (1.0 - Math.cos((Math.PI * (vibeNum - 1 - i)) / fadeLen));
                }

                samples[sampleIdx++] = volume * carrier * amMod * fade;
            }
        }

        for (let j = 0; j < pauseNum; j++) {
            samples[sampleIdx++] = 0.0;
        }
    });

    const buffer = new ArrayBuffer(44 + samples.length * 2);
    const view = new DataView(buffer);

    function writeString(offset, string) {
        for (let i = 0; i < string.length; i++) {
            view.setUint8(offset + i, string.charCodeAt(i));
        }
    }

    writeString(0, 'RIFF');
    view.setUint32(4, 36 + samples.length * 2, true);
    writeString(8, 'WAVE');
    writeString(12, 'fmt ');
    view.setUint32(16, 16, true);
    view.setUint16(20, 1, true);
    view.setUint16(22, 1, true);
    view.setUint32(24, sampleRate, true);
    view.setUint32(28, sampleRate * 2, true);
    view.setUint16(32, 2, true);
    view.setUint16(34, 16, true);
    writeString(36, 'data');
    view.setUint32(40, samples.length * 2, true);

    let offset = 44;
    for (let i = 0; i < samples.length; i++) {
        const s = Math.max(-1, Math.min(1, samples[i]));
        view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7FFF, true);
        offset += 2;
    }

    const blob = new Blob([buffer], { type: 'audio/wav' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'passive_radiator_vibration.wav';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// Event Listeners
targetDriverSelect.addEventListener('change', handleDriverChange);
carrierFreqInput.addEventListener('input', updateDisplays);
amMinFreqInput.addEventListener('input', updateDisplays);
volumeInput.addEventListener('input', updateDisplays);

btnPlayLive.addEventListener('click', startLiveAudio);
btnStopLive.addEventListener('click', stopAudio);
btnPlayPattern.addEventListener('click', playPatternSequence);
btnDownloadWav.addEventListener('click', downloadWavFile);

handleDriverChange();
